USE hr;
DELIMITER $$
CREATE FUNCTION buscar_quantidade_de_empregos_por_funcionario (EMAIL VARCHAR(100)) RETURNS INT
BEGIN
DECLARE VAGAS INT;

SELECT COUNT(J.JOB_ID)
INTO VAGAS
FROM hr.employees AS E
JOIN hr.job_history AS J
ON J.EMPLOYEE_ID = E.EMPLOYEE_ID
WHERE E.EMAIL = EMAIL;

RETURN VAGAS;
END $$
DELIMITER ;
