USE hr;
DELIMITER $$
CREATE FUNCTION exibir_quantidade_pessoas_contratadas_por_mes_e_ano (MES INT, ANO INT) RETURNS INT
BEGIN
DECLARE CONTRATADOS INT;

SELECT COUNT(E.EMPLOYEE_ID)
INTO CONTRATADOS
FROM hr.employees AS E
WHERE MONTH(HIRE_DATE) = MES AND YEAR(HIRE_DATE) = ANO;


RETURN CONTRATADOS;
END $$
DELIMITER ;
