SELECT J.JOB_TITLE AS Cargo,
CASE
WHEN J.MAX_SALARY <= 10000 THEN 'Baixo'
WHEN J.MAX_SALARY <= 20000 THEN 'Médio'
WHEN J.MAX_SALARY <= 30000 THEN 'Alto'
ELSE 'Altíssimo'
END
AS 'Nível' from hr.jobs AS J
ORDER BY Cargo ASC;
