SELECT UCASE(CONCAT(EMP.FIRST_NAME, ' ', EMP.LAST_NAME)) AS 'Nome completo',
JBH.START_DATE AS 'Data de início',
EMP.SALARY AS 'Salário'
FROM hr.job_history AS JBH
INNER JOIN hr.employees AS EMP 
ON JBH.EMPLOYEE_ID = EMP.EMPLOYEE_ID
WHERE MONTH(jbh.START_DATE) BETWEEN 1 AND 3
ORDER BY CONCAT(emp.FIRST_NAME, ' ', emp.LAST_NAME), jbh.START_DATE;
