SELECT CONCAT(EMP.FIRST_NAME, ' ', EMP.LAST_NAME) AS 'Nome completo',
JB.JOB_TITLE AS 'Cargo',
JBH.START_DATE AS 'Data de início do cargo',
DP.DEPARTMENT_NAME AS 'Departamento'
FROM hr.employees AS EMP
INNER JOIN hr.job_history AS JBH ON (EMP.EMPLOYEE_ID = JBH.EMPLOYEE_ID)
INNER JOIN hr.jobs AS JB ON (JB.JOB_ID = JBH.JOB_ID)
INNER JOIN hr.departments AS DP ON (JBH.DEPARTMENT_ID = DP.DEPARTMENT_ID)
ORDER BY CONCAT(EMP.FIRST_NAME, ' ', EMP.LAST_NAME) DESC, Cargo;
